name: Build

on:
  push:
    branch: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        ref: master
    - name: update submodule
      run: make git-submodule
    - uses: actions/checkout@v3
      with:
        path: qmk
    - name: move file
      run: |
        cp -r qmk/keyboards/* ./keyboards/
    - name: install tools
      run: |
        sudo apt install -y python3-pip
        python3 -m pip install --user qmk
        qmk setup

        sudo apt install -y gcc-avr avr-libc
    - name: build
      run: |
        RGBLIGHT_ENABLE=true make ergodox_ez:default
    - name: Create Release
      run: |
        DATE=$(TZ=JST-9 date '%M-%d_%H-%M-%S')
        gh release create $DATE ./ergodox_ez_base_my_custom.hex
