name: Build

on:
  push:
    branch: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: qmkfm/qmk_cli
    steps:
    - name: build
      run: |
        cd /qmk_firmware
        qmk --help
        qmk compile -kb ergodox_ez -km keymap
