name: Build

on:
  push:
    branch: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: move file
      run: |
        cp -r ./keyboards/* ./qmk_firmware/keyboards/
        find ./qmk_firmware/keyboards/ | grep "keymap\.c$"
    - name: install tools
      run: |
        sudo apt install -y python3-pip
        python3 -m pip install --user qmk
        qmk setup

        sudo apt install -y gcc-avr avr-libc
    - name: build
      run: |
        cd qmk_firmware
        RGBLIGHT_ENABLE=true make ergodox_ez:my_custom
    - name: find hex
      run: |
        find . | grep "\.hex$"
    - name: Create Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        DATE=$(TZ=JST-9 date +"%M-%d_%H-%M-%S")
        gh release create $DATE ./qmk_firmware/ergodox_ez_base_my_custom.hex
