name: Build

on:
  push:
    branch: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        ref: master
    - name: install tools
      run: |
        rm -rf keyboards
        rm -rf .git
    - uses: actions/checkout@v3
      with:
        path: keyboards
    - name: setup
      run: |
        sudo apt install -y git python3-pip
        python3 -m pip install --user qmk
        qmk setup
    - name: ls
      run: |
        ls -al
    - name: ls keyboards
      run: |
        find keyboards
    - name: build
      run: |
        make -kb ergodox_ez -km my_custom
        find . | grep hex
