name: Build

on:
  push:
    branch: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: https://github.com/qmk/qmk_firmware
        ref: master
    - name: install tools
      run: |
        rm -rf keyboards
    - uses: actions/checkout@v3
      with:
        path: keyboards
    - name: build
      run: |
        make keyboard=ergodox_ez keymap=keymap
