name: Build

on:
  push:
    branch: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install tools
      run: |
        curl https://linux.qmk.fm/gpg_pubkey.txt | sudo apt-key add -
        apt update
        apt install qmk
    - name: build
      run: |
        qmk --help
        qmk coompile --help
        qmk compile -kb ergodox_ez -km keymap
