name: Build

on:
  push:
    branch: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install tools
      run: |
        deb https://linux.qmk.fm/ `cat /etc/os-release | grep VERSION_CODENAME | sed s/VERSION_CODENAME=//` main
    - name: build
      run: |
        qmk --help
        qmk coompile --help
        qmk compile -kb ergodox_ez -km keymap
