name: Build

on:
  push:
    branch: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install tools
      run: |
        CODENAME=$(cat /etc/os-release | grep VERSION_CODENAME | sed s/VERSION_CODENAME=//)
        
        sudo echo "deb https://linux.qmk.fm/ $CODENAME main" >> /etc/apt/sources.list

        curl https://linux.qmk.fm/gpg_pubkey.txt | sudo apt-key add -
        sudo apt update
        sudo apt install qmk
    - name: build
      run: |
        qmk --help
        qmk coompile --help
        qmk compile -kb ergodox_ez -km keymap
